core/data_playback: false
core/fixed_bias: 0

#########IMU PARAMETERS#######
core/core_noise_acc: 0.08
core/core_noise_accbias: 0.008
core/core_noise_gyr: 0.008
core/core_noise_gyrbias: 0.00062

pose_sensor/fixed_scale: 1
pose_sensor/pose_noise_scale: 0.0
pose_sensor/pose_noise_p_wv: 0.0
pose_sensor/pose_noise_q_wv: 0.0
pose_sensor/pose_noise_q_ic: 0.01
pose_sensor/pose_noise_p_ic: 0.001
pose_sensor/pose_delay: 0.01        # Increase this value to 'foresee' oscillations. Don't go higher than 0.1s.
pose_sensor/pose_noise_meas_p: 0.01 # 0.005
pose_sensor/pose_noise_meas_q: 0.01 # 0.05

pose_sensor/init/q_ic/w: 1
pose_sensor/init/q_ic/x: 0.0
pose_sensor/init/q_ic/y: 0.0
pose_sensor/init/q_ic/z: 0.0
# Kea
#pose_sensor/init/p_ic/x: 0.019
#pose_sensor/init/p_ic/y: 0.012
#pose_sensor/init/p_ic/z: -0.0325
# Ouzel
#pose_sensor/init/p_ic/x: -0.039
#pose_sensor/init/p_ic/y: 0.0
#pose_sensor/init/p_ic/z: -0.024
pose_sensor/init/p_ic/x: 0.0
pose_sensor/init/p_ic/y: 0.0
pose_sensor/init/p_ic/z: 0.0

pose_sensor/pose_fixed_scale: true
pose_sensor/pose_fixed_p_ic: true   # Set this to false if you want to estimate translation between vicon and PX4 IMU
pose_sensor/pose_fixed_q_ic: true
pose_sensor/pose_fixed_p_wv: true
pose_sensor/pose_fixed_q_wv: true

pose_sensor/pose_absolute_measurements: true
pose_sensor/pose_use_fixed_covariance: true
pose_sensor/pose_measurement_world_sensor: true  # selects if sensor measures its position w.r.t. world (true, e.g. Vicon) or the position of the world coordinate system w.r.t. the sensor (false, e.g. ethzasl_ptam

pose_sensor/enable_mah_outlier_rejection: true
pose_sensor/mah_threshold: 20
pose_sensor/pose_measurement_minimum_dt: 0.005
